# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=250)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Classification')),
            ],
        ),
    ]
