# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('1', 'NEW'), ('2', 'PROCESSING'), ('3', 'TREATED')], default='1', max_length=1),
        ),
    ]
