# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_property'),
        ('mail', '0002_auto_20170515_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Classification')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('1', 'NEW'), ('2', 'PROCESSING'), ('3', 'CLASSIFIED')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='messageclassification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Message'),
        ),
    ]
