# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('1', 'NEW'), ('2', 'PROCESSING'), ('3', 'CLASSIFIED'), ('4', 'ANSWERED'), ('5', 'FAILURE')], default='1', max_length=1),
        ),
    ]
